# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b82f6d04e9a39d4eafaf77ebbf81c1a71819063c62294dc05ea467003ca2fa67e7feec36e83ad5632225d1839e3f09389d6d0b51bea9ec3c6e85f5193bda0e7

test:
  secret_key_base: f7a7c101e854a58011b1aeba21fb42b2e4c8020abec3b095c101dc85d60a0a9c86a10fa0a07475b5a8141fc0636be1a8336a656a9564c93ddd7922f3ba0fee51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
